[package]
name = "rasteroid"
version = "0.4.0"
description = "terminal image / video graphics ( iterm / kitty / sixel )"
keywords = ["iterm", "kitty", "sixel", "terminal", "terminal-graphics"]
categories = ["command-line-utilities", "graphics", "rendering"]
repository = "https://github.com/Skardyy/mcat"
homepage = "https://github.com/Skardyy/mcat"
documentation = "https://github.com/Skardyy/mcat"
license = "MIT"
readme = "README.md"
edition = "2024"

[dependencies]
base64.workspace = true
color_quant.workspace = true
crossterm.workspace = true
fast_image_resize.workspace = true
image = { workspace = true, features = ["png", "jpeg", "pnm"] }
rand.workspace = true
signal-hook.workspace = true
thiserror.workspace = true
rayon.workspace = true

[dev-dependencies]
ffmpeg-sidecar.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
libc.workspace = true
shared_memory_fork.workspace = true

[target."cfg(windows)".dependencies]
windows.workspace = true
